### ISSUE TITLE
How to configure to run KOA2 along with Angular CLI

### ISSUE THREAD

**Issue by sakar-sr** [zoltan-nz/koa-ts-contacts-app#1]
Please let me know how to run koa along with Angular 4 project that is created  using Angular/CLI

**Comment by zoltan-nz** [comment]
@sakar-sr I guess, you should separately create a backend with koa2, which is a REST Api microservice... meanwhile you create an Angular app, which is only the frontend. You build backend and frontend app.

**Comment by sakar-sr** [comment]
Thank you, I got the point.
